#############################################################################
##
##  aut_lambda_star.g -- structure of Aut(Lambda, +, star)
##
##  Reads the 24x24 integer matrices produced by
##      python_project/src/verify_aut_lambda_star.py
##  (three generators, expressed in the Z-basis of Wilson's Leech lattice
##  Lambda that the Python script builds by Hermite normal form), forms the
##  matrix group they generate inside GL_24(Z), and reports its order and
##  StructureDescription.
##
##  This is the SECOND, INDEPENDENT determination of the order: the Python
##  side counts the group as |K| * |S_3| = 6 * 6 by exhaustive enumeration of
##  the pairs (A,B); GAP recomputes the order of the group generated by three
##  explicit matrices by its own (Schreier-Sims / nice-monomorphism) machinery
##  and knows nothing of that enumeration.
##
##  Expected:  Size = 36,  StructureDescription = "C6 x S3".
##
#############################################################################

Read("aut_lambda_star_gens.g");

Print("number of generators: ", Length(gens), "\n");
Print("all matrices integral 24x24: ",
      ForAll(gens, m -> Length(m) = 24 and ForAll(m, r -> Length(r) = 24)
                        and ForAll(Flat(m), IsInt)), "\n");
Print("all determinants +-1: ",
      ForAll(gens, m -> AbsInt(DeterminantMat(m)) = 1), "\n");
Print("orders of the generators: ", List(gens, Order), "\n");

G := Group(gens);
Print("Size(G) = ", Size(G), "\n");
Print("StructureDescription(G) = ", StructureDescription(G), "\n");
Print("IsAbelian(G) = ", IsAbelian(G), "\n");
Print("element orders: ", SortedList(List(ConjugacyClasses(G),
        c -> Order(Representative(c)))), "\n");
Print("centre: ", StructureDescription(Centre(G)), "\n");
Print("derived subgroup: ", StructureDescription(DerivedSubgroup(G)), "\n");
Print("-I_24 in G: ", -IdentityMat(24) in G, "  (expect false)\n");
