"""Degree of span-surjectivity of the triple product: compute the exact
index [Lambda : S] of the sublattice S := Z-span{ u star v : u, v in
Lambda } inside Lambda.

By bilinearity, S is generated by the 24 x 24 = 576 basis-pair products
B_i star B_j of a Z-basis B of Lambda.  Working in L^3 coordinates
(integers), the Hermite normal form of the generator matrix gives
|det| = [L^3 : S]; dividing by [L^3 : Lambda] = 4096 gives [Lambda : S].

  [Lambda : S] = 1   <=>  the products Z-span all of Lambda
                          ("span-surjective"; the reviewer's "very
                          likely surjective" settled at the Z-span level)
  [Lambda : S] = n   <=>  products generate a proper sublattice of
                          index n (every u star v lies in S; a fraction
                          1 - 1/n of Lambda-cosets mod S is unreachable
                          even by Z-combinations of products)

Reuses the exact Z-basis and star machinery from
verify_consecutive_twists_exact.py.  All arithmetic exact.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sympy import Matrix
from sympy.matrices.normalforms import hermite_normal_form
from verify_consecutive_twists_exact import B, twisted, l3, detB, inLambda

SIGMA = (0, 2, 1, 3, 4, 5, 6, 7)          # the paper's sigma = (1 2)
star = twisted(SIGMA)

if __name__ == "__main__":
    print("=" * 70)
    print("Span-surjectivity: index of S = Z-span(Lambda star Lambda) in Lambda")
    print("=" * 70)
    print(f"[L^3 : Lambda] = {detB}  (expect 4096 = 2^12)")

    prods = []
    n_in = 0
    for bi in B:
        for bj in B:
            p = star(bi, bj)
            if inLambda(p):
                n_in += 1
            prods.append(l3(p))
    print(f"basis-pair products computed: {len(prods)}; "
          f"in Lambda: {n_in} (expect 576 by Theorem 1.1)")

    G = Matrix(prods).T                     # 24 x 576, columns = products
    H = hermite_normal_form(G)              # 24 x 24
    det_S = abs(H.det())                    # [L^3 : S]
    print(f"[L^3 : S]      = {det_S}")
    idx = det_S / detB
    print(f"[Lambda : S]   = {det_S} / {detB} = {idx}")
    if idx == 1:
        print("=> S = Lambda: the products Z-SPAN the full Leech lattice.")
    else:
        print(f"=> S is a proper sublattice of index {idx}.")
